version: '3.8'
services:
  db:
    container_name: hirakawa-db05-db
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_model05
      TZ: "Asia/Tokyo"
  pgadmin:
    user: root
    container_name: hirakawa-db05-pgadmin
    image: dpage/pgadmin4:7.3
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      TZ: Asia/Tokyo
    ports:
      - 8080:80
    depends_on:
      - db