@startuml

entity orders as "orders\n注文票" {
  * <u>order_id</u> (pk) [注文ID]
  --
  customer_id (fk) [顧客ID]
  tax_id (fk) [税率ID]
  is_take_out [持ち帰りフラグ]
  is_paid [支払い済みフラグ]
  order_date [注文日時]
}

entity order_details as "order_details\n注文詳細" {
  * <u>order_id</u> (pk, fk) [注文ID]
  * <u>item_id</u> (pk, fk) [メニュー or 寿司ID]
  --
  is_wasabi [わさびフラグ]
  case_name (fk) [化粧箱名]
  quantity [個数]
}

entity menu_shshi as "menu_shshi\n寿司メニュー" {
  * <u>sushi_id (pk)</u> [寿司ID]
  --
  shushi_name [名前]
  price [金額]
}

entity menu_courses as "menu_courses\nコースメニュー" {
  * <u>course_id</u> (pk) [コースID]
  --
  course_name [名前]
}

entity course_detail as "course_detail\nコース詳細" {
  * <u>course_detail_id</u> (pk) [コース詳細ID]
  --
  course_id (fk) [コースID]
  sushi_id (fk) [寿司ID]
}

entity cosmetic_ceses as "cosmetic_ceses\n化粧箱" {
  * <u>cosmetic_cese_id</u> (pk) [化粧箱ID]
  --
  case_name [化粧箱名]
  price [金額]
}

entity tax_rates as "tax_rates\n税率" {
  * <u>tax_id</u> (pk) [税率ID]
  --
  rate [税率]
}

entity customers as "customers\n顧客情報" {
  * <u>customer_id</u> (pk) [顧客ID]
  --
  customer_name [名前]
  phone_number [電話番号]
}

orders ||--|{ order_details
order_details ||..o{ menu_courses
order_details ||..o{ menu_shshi
menu_courses ||--|{ course_detail
course_detail ||--|{ menu_shshi
order_details ||..o{ cosmetic_ceses
orders }o..|| tax_rates
orders }o..|| customers

' 1 対 0 または 1
'   users ||..o| user_details
' 1 対 1
'   users ||..|| user_details
' 1 対 0 以上
'   users ||..o{ user_items
' 1 対 1 以上
'   users ||..|{ user_items

@enduml
