@startuml osushi_table

!define MASTER F9DFD5
!define TRANSACTION CAE7F2

entity users as "users\nユーザー" <<T, TRANSACTION>> {
    id BIGSERIAL INT
    +uuid VARCHAR(255)
    --
    name VARCHAR(255) [名前]
    display_name VARCHAR(255) [表示名]
    email VARCHAR(255) [名(かな)]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity belonging_to_workspaces as "belonging_to_workspaces\n所属(ワークスペース)" <<T, TRANSACTION>>  {
    id BIGSERIAL INT
    +uuid VARCHAR(255)
    --
    user_id: VARCHAR(255) [ユーザーID]
    workspace_id VARCHAR(255) [ワークスペースID]
    name VARCHAR(255) [名前]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity belonging_to_channels as "belonging_to_channels\n所属(チャンネル)" <<T, TRANSACTION>>  {
    id BIGSERIAL INT
    +uuid VARCHAR(255)
    --
    user_id: VARCHAR(255) [ユーザーID]
    channel_id VARCHAR(255) [チャンネルID]
    name VARCHAR(255) [名前]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity posts as "posts\n投稿" <<T, TRANSACTION>>  {
    id BIGSERIAL INT
    +uuid VARCHAR(255)
    --
    user_id VARCHAR(255) [ユーザーID]
    channel_id VARCHAR(255) [チャンネルID]
    parent_id VARCHAR(255) [親のID]
    body TEXT [投稿内容]
    delete_flg BOOLEAN [論理削除フラグ]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity channels as "channels\nチャンネル" <<T, TRANSACTION>>  {
    id BIGSERIAL INT
    +uuid VARCHAR(255)
    --
    name VARCHAR(255) [名前]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity workspaces as "workspaces\nワークスペース" <<T, TRANSACTION>>  {
    id BIGSERIAL INT
    +uuid VARCHAR(255)
    --
    name VARCHAR(255) [名前]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

users --|{ belonging_to_workspaces
users --|{ belonging_to_channels
belonging_to_workspaces }-- workspaces
belonging_to_channels }-- channels 
posts }|-- users
posts }-- channels