INSERT INTO User (id, name, display_name, email, password)
VALUES (
    null,
    '平川知秀',
    'ユーザー1',
    'hirakawa@test.com',
    'xxxxxxxxxxxxxxxxxxxxxx'
  ),
  (
    null,
    '田中秀樹',
    'ユーザー2',
    'tanaka@gmail.com',
    'xxxxxxxxxxxxxxxxxxxxxx'
  ),
  (
    null,
    '佐藤正雄',
    'ユーザー3',
    'tanaka@gmail.com',
    'xxxxxxxxxxxxxxxxxxxxxx'
  ),
  (
    null,
    '秋山信二',
    'ユーザー4',
    'tanaka@gmail.com',
    'xxxxxxxxxxxxxxxxxxxxxx'
  );