@startuml

!define MASTER F9DFD5
!define TRANSACTION CAE7F2

entity "product" as product <<M,MASTER>> {
    + id: INT <<PK>>
    --
    product_code: VARCHAR(255)
    name: VARCHAR(255)
    deleted_at: TIMESTAMP
}

@enduml