@startuml

!define MASTER F9DFD5
!define TRANSACTION CAE7F2

package database <<Database>> {
  entity categories as "category\nカテゴリー" <<M,MASTER>> {
    + id INT(10) [PK]
    --
    name TEXT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity menus as "menu\nメニュー" <<M,MASTER>> {
    + id INT(10) [PK]
    --
    name TEXT
    price INT
    category_id INT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
    entity options as "option\nオプション" <<M,MASTER>> {
    + id INT(10) [PK]
    --
    name TEXT
    price INT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity orders as "order\n注文" <<T,TRANSACTION>> {
    + id INT(10) [PK]
    --
    orderer TEXT
    phone TEXT
    paid BOOLEAN
    checked_number_of_orders INT
    request TEXT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity order_menus as "order_menu\norderとmenuの中間テーブル" <<T,TRANSACTION>> {
    + id INT(10) [PK]
    --
    orderer_id INT
    menu_id INT
    number INT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity order_menu_options as "order_menu_option\n order_menuとoptionの中間テーブル" <<T,TRANSACTION>> {
    + id INT(10) [PK]
    --
    order_menu_id INT
    option_id INT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  categories ||-ri-o{ menus
  menus ||-ri-o{ order_menus
  orders ||-le-|{ order_menus
  options ||-up-o{ order_menu_options
  order_menus ||-down-o{ order_menu_options
}


@enduml