@startuml

!define MASTER F9DFD5
!define TRANSACTION CAE7F2

package database <<Database>> {
  entity category as "category\nカテゴリー" <<M,MASTER>> {
    + id INT(10) [PK, autonumber]
    --
    name TEXT
    is_combo BOOLEAN
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity menu as "menu\nメニュー" <<M,MASTER>> {
    + id INT(10) [PK, autonumber]
    --
    name TEXT
    price DECIMAL(10, 2)
    can_takeaway: BOOLEAN
    category_id [FK(category,id)]
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity option as "option\nオプション" <<M,MASTER>> {
    + id INT(10) [PK, autonumber]
    --
    name TEXT
    price DECIMAL(10, 2)
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity customer as "customer\nお客さん" <<T,TRANSACTION>> {
    + id INT(10) [PK, autonumber]
    --
    name TEXT
    phone_number VARCHAR
  }
  
  entity order as "order\n注文" <<T,TRANSACTION>> {
    + id INT(10) [PK, autonumber]
    --
    customer_id [FK(customer,id)]
    paid BOOLEAN
    request TEXT
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity order_menu as "order_menu\n注文詳細テーブル" <<T,TRANSACTION>> {
    + id INT(10) [PK, autonumber]
    --
    orderer_id [FK(orderer,id)]
    menu_id [FK(menu,id)]
    number INT
    price DECIMAL(10, 2)
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
    entity menu_option as "menu_option\nオプション追加可能メニューテーブル" <<T,TRANSACTION>> {
    + id INT(10) [PK, autonumber]
    --
    menu_id [FK(menu,id)]
    option_id [FK(option,id)]
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  entity order_menu_option as "order_menu_option\n注文詳細オプション内容テーブル" <<T,TRANSACTION>> {
    + id INT(10) [PK, autonumber]
    --
    order_menu_id [FK(menu,id)]
    option_id [FK(option,id)]
    updated_at TIMESTAMP
    created_at TIMESTAMP
  }
  
  category ||-right-o{ menu
  menu ||-right-o{ order_menu
  menu ||-down-o{ menu_option
  customer ||-le-|{ order
  order ||-left-|{ order_menu
  option ||-up-o{ order_menu_option
  option ||-left-o{ menu_option
  order_menu ||-down-o{ order_menu_option
}


@enduml