START TRANSACTION;

DROP TABLE IF EXISTS `content_details`;
DROP TABLE IF EXISTS `contents`;
DROP TABLE IF EXISTS `accounts`;

CREATE TABLE accounts (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE contents (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    account_id INT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET NULL
);

CREATE TABLE content_details (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    content_id INT NOT NULL,
    content_title VARCHAR(255) NOT NULL,
    content_body TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_at  TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE
);

COMMIT;