@startuml usecase 

object 管理者 {
    管理者ID
    メールアドレス
}

note left of 管理者 
- 新規参加者を追加できる
- 参加者の変動により管理者の調整が必要な場合メールを受信。
    - 参加者にヒアリングして、ペアを編成する。
- 詳細は、「参加者の増減に関する仕様」を参照
end note

object 課題 {
    課題番号
    課題タイトル
    課題ジャンル
    学ばないと何が起きるか
    課題説明
}

note right of 課題 
- 全ての参加者は複数の課題（80個ぐらい）を所有（割り当てられて）いる
end note

object 課題進捗 {
    課題ID
    ユーザーID
    課題進捗
}

note bottom of 課題進捗 
- 課題には、参加者ごとに進捗ステータスがある
    - 進捗ステータスは「未着手、レビュー待ち、完了」いずれかの値を持つ
    - 進捗ステータスはいつでも変更可能
    - ただし一度「完了」にした進捗ステータスを「レビュー待ち」「未着手」に戻すことはできない
    - 進捗ステータスを変更できるのは、課題の所有者だけ
end note

rectangle チーム集約 {
    object 参加者 {
        参加者ID
        参加者名
        メールアドレス
        所属チーム
        所属ペア
        在籍状況
    }
    object ペア {
        ペア名
        ペアメンバー
    }
    object チーム {
        チーム名
        チームメンバー
    }
}

note bottom of 参加者 
- 名前とメールアドレスを持つ
    - メールアドレスの重複は許容されない
- メールアドレスの重複は許容されない
    - ステータスが「在籍中」ではない場合、
    どのチームにもペアにも所属してはいけない
end note

note right of ペア 
- ペアには名前がある（a,b,c,d,eのような英文字でなければいけない)
    - ペア名は1文字でなければいけない
- 参加者は2名〜3名まで。1名のペアや、4名のペアは存在できない
- ペアの人数が変動した時の挙動については以下の「参加者の増減に関する仕様」を参照してください
- ペアは必ず同じチームの参加者から選ばれます（チーム1とチーム2の参加者がペアを組むことはありません）
end note

note right of チーム
- チームには名前がある
    - チームの名前は1,2,3,4のような数字でなければいけない
    - チームの名前は重複不可
    - チームの名前は3文字以下でなければいけない
- チームには最低でも参加者が3名いなければならない。
- 2名以下になった時の挙動については以下の「参加者の増減に関する仕様」を参照
end note

note top of チーム集約 
- 相互に影響を与え合う関係性な為、１つの集約に
end note

管理者 o--> 参加者 : has-many

参加者 o--> 課題進捗 : has-many

課題 o--> 課題進捗 : has-many

ペア o--> 参加者 : has-many

チーム o--> ペア : has-many

@enduml