@startuml usecase 
left to right direction

:参加者: as participant

:管理者: as manager

note left of participant 
- 名前とメールアドレスを持つ
    - メールアドレスの重複は許容されない
- メールアドレスの重複は許容されない
    - ステータスが「在籍中」ではない場合、
    どのチームにもペアにも所属してはいけない
end note

note bottom of manager 
- 参加者の変動により管理者の調整が必要な場合メールを受信。
    - 参加者にヒアリングして、ペアを編成する。
- 詳細は、「参加者の増減に関する仕様」を参照
end note

rectangle 全メンバー as all_member {
    usecase "参加者の一覧取得" as UC1_1
    rectangle チーム as tearm {
        usecase "チームの一覧取得" as UC2_1
        rectangle ペア as pair {
            usecase "ペアの一覧取得" as UC3_1
        }
    }
}

note right of tearm
- チームには名前がある
    - チームの名前は1,2,3,4のような数字でなければいけない
    - チームの名前は重複不可
    - チームの名前は3文字以下でなければいけない
- チームには最低でも参加者が3名いなければならない。
- 2名以下になった時の挙動については以下の「参加者の増減に関する仕様」を参照
end note

note right of pair 
- ペアには名前がある（a,b,c,d,eのような英文字でなければいけない)
    - ペア名は1文字でなければいけない
- 参加者は2名〜3名まで。1名のペアや、4名のペアは存在できない
- ペアの人数が変動した時の挙動については以下の「参加者の増減に関する仕様」を参照してください
- ペアは必ず同じチームの参加者から選ばれます（チーム1とチーム2の参加者がペアを組むことはありません）
end note

rectangle 課題 as task {
    usecase "課題の進捗を変更する" as UC4_1
    usecase "課題の取得絞り込み" as UC4_2
}

note right of task 
- 全ての参加者は複数の課題（80個ぐらい）を所有（割り当てられて）いる
- 課題には、参加者ごとに進捗ステータスがある
    - 進捗ステータスは「未着手、レビュー待ち、完了」いずれかの値を持つ
    - 進捗ステータスはいつでも変更可能
    - ただし一度「完了」にした進捗ステータスを「レビュー待ち」「未着手」に戻すことはできない
    - 進捗ステータスを変更できるのは、課題の所有者だけ
end note

rectangle 在籍ステータス as enrollment_status {
    usecase "休会・退会する" as UC5_1
    usecase "復帰する" as UC5_2
}

note right of enrollment_status 
- 在籍ステータスを持つ。取りうる値は「在籍中」「休会中」「退会済」の3つ
- ステータスが「在籍中」ではない場合、どのチームにもペアにも所属してはいけない
end note

participant --> UC1_1
participant --> UC2_1
participant --> UC3_1
participant --> UC4_1
participant --> UC4_2
participant --> UC5_1
participant --> UC5_2
enrollment_status --> manager

@enduml