@startuml single_item_table

!define MASTER F9DFD5
!define TRANSACTION CAE7F2

entity customers as "customers\n注文者" <<T, TRANSACTION>>  {
    id BIGSERIAL [PK]
    +uuid VARCHAR(255)
    --
    first_name VARCHAR(255) [名] NOT NULL,
    last_name VARCHAR(255) [姓] NOT NULL,
    phone_number VARCHAR(255) [電話番号], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity orders as "orders\n注文" <<T, TRANSACTION>> {
    + id BIGSERIAL [PK]
    +uuid VARCHAR(255)
    --
    # customer_id [FK], NOT NULL
    comments TEXT [自由記述欄]
    is_paid BOOLEAN [支払いの有無], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity single_item_order_detail as "single_item_order_detail\n単品注文詳細" <<T, TRANSACTION>>  {
    + id BIGSERIAL [PK]
    +uuid VARCHAR(255)
    --
    # order_id [FK], NOT NULL
    # single_item_id [FK], NOT NULL
    has_wasabi BOOLEAN [わさびの有無], NOT NULL, DEFAULT: TRUE
    count INTEGER [個数], NOT NULL, DEFAULT: 0
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity set_menu_order_detail as "set_menu_order_detail\nセットメニュー注文詳細" <<T, TRANSACTION>>  {
    + id BIGSERIAL [PK]
    +uuid VARCHAR(255)
    --
    # order_id [FK], NOT NULL
    # set_menu_id [FK], NOT NULL
    has_wasabi BOOLEAN [わさびの有無], NOT NULL, DEFAULT: TRUE
    count INTEGER [個数], NOT NULL, DEFAULT: 0
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity single_items as "single_items\n単品" <<M, MASTER>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    # single_item_category_id [FK], NOT NULL
    name VARCHAR(255) [お寿司の名前], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity single_item_categories as "single_item_categories\n単品のカテゴリー" <<M, MASTER>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    name VARCHAR(255) [分類名], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity single_item_price_relations as "single_item_price_relations\n単品の価格" <<T, TRANSACTION>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    # single_item_id [FK], NOT NULL
    # price_id [FK], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity set_menu as "set_menu\nセットメニュー" <<M, MASTER>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    # set_menu_category_id [FK], NOT NULL
    name VARCHAR(255) [セットメニューの名前], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity set_menu_categories as "set_menu_categories\nセットメニューカテゴリー" <<M, MASTER>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    name VARCHAR(255) [分類名], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity set_menu_price_relations as "set_menu_price_relations\nセットメニューの価格" <<T, TRANSACTION>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    # set_menu_id [FK], NOT NULL
    # price_id [FK], NOT NULL
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

entity price as "price\n価格" <<M, MASTER>> {
    + id SERIAL [PK]
    +uuid VARCHAR(255)
    --
    price INT [税抜価格], NOT NULL
    started_at TIMESTAMP [適用開始日], NOT NULL
    ended_at TIMESTAMP [適用終了日]
    created_at TIMESTAMP
    updated_at TIMESTAMP
}

customers --|{ orders
orders --o{ single_item_order_detail
orders --o{ set_menu_order_detail
single_item_order_detail }|-- single_items
set_menu_order_detail }|-- set_menu
single_items }|-right- single_item_categories
set_menu }|-down- set_menu_categories
single_items }|-- single_item_price_relations
price }|-up- single_item_price_relations
set_menu }|-- set_menu_price_relations
price }|-up- set_menu_price_relations

@enduml