DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `post`;

-- Postテーブルの作成
CREATE TABLE post (
    id VARCHAR(255) PRIMARY KEY,
    text VARCHAR(255) UNIQUE NOT NULL,
    tag1 VARCHAR(255) NULL DEFAULT NULL,
    tag2 VARCHAR(255) NULL DEFAULT NULL,
    tag3 VARCHAR(255) NULL DEFAULT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tagテーブルの作成
CREATE TABLE tag (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;