erDiagram

users ||--o{ orders: ""
orders ||--|{ order_items: ""
orders }o--|| payment_statuses: ""
orders }o--|| tax_rates: ""
orders }o--|| provide_methods: ""
orders }o--|| packagings: ""
order_items ||--|{ order_item_products: ""
order_items ||--o{ order_item_optional_menus: ""
order_item_optional_menus }o--|| optional_menus: ""
order_item_products }o--|| products: ""
products ||--o{ product_logs: ""
product_logs }o--|| tax_rates: ""
product_log_provide_methods }|--|| product_logs: ""
product_log_provide_methods }o--|| provide_methods: ""
product_log_families }o--o{ product_logs: ""
categories ||--o{ product_log_categories: ""
product_logs ||--o{ product_log_categories: ""
guest_users ||--o{ orders: ""
users ||--o{ user_coupons: ""
user_coupons }o--|| coupons: ""
coupons }o--|| coupon_types: ""
guest_users ||--o{ user_coupons: ""

users {
  id bigint PK
  name varchar(255)
  phone varchar(11)
  email varchar(255)
  crypted_password varchar(255)
  salt varchar(255)
}

guest_users {
  id bigint PK
  name varchar(255)
  phone varchar(11)
  email varchar(255)
}

user_coupons {
  id bigint PK
  user_id bigint FK
  coupon_id bigint FK
  used_at datetime
}

coupons {
  id bigint PK
  is_available boolean
  name varchar(255)
  coupon_code varchar(255)
  discount_price int
  coupon_type_id bigint FK
  expiration_at datetime
}

coupon_types {
  id bigint PK
  name varchar(255)
}

orders {
  id bigint PK
  ordered_at datetime
  total_quantity int
  sub_total_price int
  total_price int
  payment_status_id bigint FK
  provide_method_id bigint FK
  payment_completed_at datetime
  user_id bigint FK
  tax_rate_id bigint FK
  packaging_id bigint FK
}

packagings {
  id bigint PK
  name varchar(255)
}

payment_statuses {
  id bigint PK
  name varchar(255)
}

order_items {
  id bigint PK
  quantity int
  cancel_quantity int
  sub_total_price int
  total_price int
  order_id bigint FK
}

order_item_optional_menus {
  id bigint PK
  order_item_id bigint FK
  optional_menu_id bigint FK
}

optional_menus {
  id bigint PK
  name varchar(255)
}

order_item_products {
  id bigint PK
  order_item_id bigint FK
  product_id bigint FK
}

products {
  id bigint PK
}

product_logs {
  id bigint PK
  name varchar(255)
  price int
  provide_method_id bigint FK
  tax_rate_id bigint FK
  product_id bigint
  created_at datetime
  updated_at datetime
}

product_log_provide_methods {
  id bigint PK
  product_]og_id bigint FK
  provide_method_id bigint
}

product_log_families {
  id bigint PK
  parent_id bigint FK
  child_id bigin FK
}

provide_methods {
  id bigint PK
  name varchar(255)
}

product_log_categories {
  id bigint PK
  product_log_id bigint FK
  category_id bigint FK
}

categories {
  id bigint PK
  name varchar(255)
}

tax_rates {
  id bigint PK
  tax_percentage int
}