version: '3'

services:
  db:
    image: postgres:14
    container_name: modeling05
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: user
      POSTGRES_DB : modelingPractice
      TZ: "Asia/Tokyo"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
volumes:
  db-store: