-- users
INSERT INTO users (username, email, password, display_name, profile_image_url) VALUES
('user1', 'user1@example.com', 'password1', 'ユーザー1', 'https://example.com/image1.jpg'),
('user2', 'user2@example.com', 'password2', 'ユーザー2', 'https://example.com/image2.jpg'),
('user3', 'user3@example.com', 'password3', 'ユーザー3', 'https://example.com/image3.jpg'),
('user4', 'user4@example.com', 'password4', 'ユーザー4', 'https://example.com/image4.jpg'),
('user5', 'user5@example.com', 'password5', 'ユーザー5', 'https://example.com/image5.jpg');

-- workspaces
INSERT INTO workspaces (name) VALUES
('workspace1'),
('workspace2'),
('workspace3');

-- workspace_members
INSERT INTO workspace_members (user_id, workspace_id, role) VALUES
(1, 1, 0),
(2, 1, 1),
(3, 1, 1),
(4, 1, 1),
(1, 2, 0),
(2, 2, 1),
(3, 2, 1),
(4, 3, 0),
(1, 3, 1),
(5, 3, 1);

-- channels
INSERT INTO channels (workspace_id, name, description, is_private) VALUES
(1, 'general', '一般チャンネル', false),
(1, 'random', 'ランダムな話題', false),
(1, 'private1', 'プライベートチャンネル1', true),
(2, 'general', '一般チャンネル', false),
(2, 'news', 'ニュース', false),
(3, 'general', '一般チャンネル', false),
(3, 'random', 'ランダムな話題', false);

-- channel_members
INSERT INTO channel_members (user_id, channel_id) VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(1, 2),
(2, 2),
(3, 2),
(4, 2),
(5, 2),
(1, 3),
(2, 3),
(3, 3),
(4, 3),
(5, 3),
(1, 4),
(2, 4),
(3, 4),
(4, 4),
(5, 4),
(1, 5),
(2, 5),
(3, 5);

-- messages
INSERT INTO messages (user_id, channel_id, content) VALUES
(1, 1, 'こんにちは、これはテストメッセージです。'),
(2, 1, 'Hello, this is a test message.'),
(3, 1, '初めまして、ユーザー3です。'),
(4, 1, 'Nice to meet you all!'),
(1, 1, 'コードの例:\n```\nprint("Hello, World!")\n```'),
(2, 1, '例のコード:\n```\ndef greet(name):\n    return f"Hello, {name}!"\nprint(greet("John"))\n```'),
(3, 1, '日本語のメッセージです。'),
(4, 1, 'Another English message.'),
(1, 1, '今日の天気は晴れです。'),
(2, 1, "Today's weather is sunny."),
(3, 1, '昨日は雨でした。'),
(4, 1, 'It was raining yesterday.'),
(1, 1, 'どんなプログラミング言語が好きですか？'),
(2, 1, 'What programming languages do you like?'),
(3, 1, 'PythonとJavaScriptが好きです。'),
(4, 1, 'I like Python and JavaScript.'),
(1, 1, '最近読んだ本は何ですか？'),
(2, 1, 'What is the recent book you read?'),
(3, 1, '『嫌われる勇気』を読みました。'),
(4, 1, 'I read "The Courage to be Disliked".'),
(1, 1, 'おすすめの映画は何ですか？'),
(2, 1, 'What movie do you recommend?'),
(3, 1, '『千と千尋の神隠し』が好きです。'),
(4, 1, 'I like "Spirited Away".'),
(1, 1, 'データベースの設計について教えてください。'),
(2, 1, 'Please tell me about database design.'),
(3, 1, '正規化とインデックスを理解することが重要です。'),
(4, 1, 'Understanding normalization and indexes is important.'),
(1, 1, 'フロントエンドとバックエンドの違いは何ですか？'),
(2, 1, 'What is the difference between frontend and backend?'),
(3, 1, 'フロントエンドはUI/UX、バックエンドはサーバーサイドの処理です。'),
(4, 1, 'Frontend deals with UI/UX, while backend handles server-side processing.');

-- threads
INSERT INTO threads (parent_message_id, user_id, content) VALUES
(1, 2, 'こんにちは、返信です。'),
(1, 3, 'Hello, this is a reply.'),
(1, 4, 'こちらも返信です。'),
(2, 1, 'Reply to the English message.'),
(2, 3, '英語のメッセージへの返信です。'),
(3, 1, 'Nice to meet you, user3!'),
(3, 2, 'ユーザー3さん、はじめまして！'),
(4, 3, 'Thank you!'),
(4, 4, 'ありがとう！'),
(5, 1, 'いいコードの例ですね！'),
(5, 2, 'Great code example!'),
(6, 3, 'コードの例が役立ちました！'),
(6, 4, 'The code example was helpful!'),
(7, 1, 'もっと詳しく教えてください。'),
(7, 2, 'Please provide more details.'),
(8, 3, '詳細について質問があります。'),
(8, 4, 'I have a question about the details.'),
(9, 1, '次のステップは何ですか？'),
(9, 2, 'What is the next step?'),
(10, 3, 'これからどうすればいいですか？'),
(10, 4, 'What should we do next?'),
(11, 1, '追加情報が必要です。'),
(11, 2, 'More information is needed.'),
(12, 3, 'もっと情報が欲しいです。'),
(12, 4, 'I would like more information.'),
(13, 1, 'コードの説明が分かりやすいです。'),
(13, 2, 'The code explanation is clear.'),
(14, 3, 'コードの解説が理解しやすいです。'),
(14, 4, 'The code explanation is easy to understand.'),
(15, 1, 'この問題をどのように解決しましたか？'),
(15, 2, 'How did you solve this problem?'),
(16, 3, '問題の解決方法を教えてください。'),
(16, 4, 'Please share your solution to the problem.'),
(17, 1, '参考になるリソースを教えてください。'),
(17, 2, 'Can you share some helpful resources?'),
(18, 3, '役立つリソースがあれば教えてください。'),
(18, 4, 'Please let me know if you have any useful resources.'),
(19, 1, '次回のミーティングはいつですか？'),
(19, 2, 'When is the next meeting?'),
(20, 3, '次の会合はいつですか？'),
(20, 4, 'When do we meet next time?'),
(21, 1, 'この機能の実装方法を教えてください。'),
(21, 2, 'How can I implement this feature?'),
(22, 3, 'この機能をどうやって実装するのですか？'),
(22, 4, 'What is the way to implement this functionality?'),
(23, 1, 'このエラーはどう解決しますか？'),
(23, 2, 'How can I fix this error?'),
(24, 3, 'このエラーの解決策は何ですか？'),
(24, 4, 'What is the solution for this error?'),
(25, 1, 'どのようにデバッグすればいいですか？'),
(25, 2, 'How should I debug this?'),
(26, 3, 'デバッグ方法を教えてください。'),
(26, 4, 'Please tell me how to debug this.'),
(27, 1, '最適化方法を教えてください。'),
(27, 2, 'What is the best way to optimize this?'),
(28, 3, 'このコードを最適化する方法は何ですか？'),
(28, 4, 'How can I optimize this code?'),
(29, 1, 'プロジェクトの進捗状況はどうですか？'),
(29, 2, 'What is the status of the project?'),
(30, 3, 'プロジェクトの進行状況を教えてください。'),
(30, 4, 'Please update me on the project progress.');