version: '3'

services:
  db:
    image: postgres:latest
    container_name: modeling04
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: user
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres-db-store:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
volumes:
  postgres-db-store: